# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chainfunction.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='chainfunction.proto',
    package='proto_gen',
    syntax='proto3',
    serialized_options=b'Zegithub.com/vhive-serverless/stellar/src/setup/deployment/raw-code/producer-consumer/go1.x/vhive/proto_gen',
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x13\x63hainfunction.proto\x12\tproto_gen\"\xcd\x01\n\x12InvokeChainRequest\x12\x16\n\x0eincrementLimit\x18\x01 \x01(\t\x12\x1c\n\x14\x64\x61taTransferChainIDs\x18\x02 \x01(\t\x12\x1a\n\x12payloadLengthBytes\x18\x03 \x01(\t\x12\x17\n\x0ftransferPayload\x18\x04 \x01(\t\x12\x16\n\x0etimestampChain\x18\x05 \x01(\t\x12\x0e\n\x06\x62ucket\x18\x06 \x01(\t\x12\x0b\n\x03key\x18\x07 \x01(\t\x12\x17\n\x0fstorageTransfer\x18\x08 \x01(\x08\"*\n\x10InvokeChainReply\x12\x16\n\x0etimestampChain\x18\x01 \x01(\t2^\n\x10ProducerConsumer\x12J\n\nInvokeNext\x12\x1d.proto_gen.InvokeChainRequest\x1a\x1b.proto_gen.InvokeChainReply\"\x00\x42gZegithub.com/vhive-serverless/stellar/src/setup/deployment/raw-code/producer-consumer/go1.x/vhive/proto_genb\x06proto3'
)

_INVOKECHAINREQUEST = _descriptor.Descriptor(
    name='InvokeChainRequest',
    full_name='proto_gen.InvokeChainRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='incrementLimit', full_name='proto_gen.InvokeChainRequest.incrementLimit', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='dataTransferChainIDs', full_name='proto_gen.InvokeChainRequest.dataTransferChainIDs', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='payloadLengthBytes', full_name='proto_gen.InvokeChainRequest.payloadLengthBytes', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='transferPayload', full_name='proto_gen.InvokeChainRequest.transferPayload', index=3,
            number=4, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='timestampChain', full_name='proto_gen.InvokeChainRequest.timestampChain', index=4,
            number=5, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='bucket', full_name='proto_gen.InvokeChainRequest.bucket', index=5,
            number=6, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='key', full_name='proto_gen.InvokeChainRequest.key', index=6,
            number=7, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='storageTransfer', full_name='proto_gen.InvokeChainRequest.storageTransfer', index=7,
            number=8, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=35,
    serialized_end=240,
)

_INVOKECHAINREPLY = _descriptor.Descriptor(
    name='InvokeChainReply',
    full_name='proto_gen.InvokeChainReply',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='timestampChain', full_name='proto_gen.InvokeChainReply.timestampChain', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=242,
    serialized_end=284,
)

DESCRIPTOR.message_types_by_name['InvokeChainRequest'] = _INVOKECHAINREQUEST
DESCRIPTOR.message_types_by_name['InvokeChainReply'] = _INVOKECHAINREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InvokeChainRequest = _reflection.GeneratedProtocolMessageType('InvokeChainRequest', (_message.Message,), {
    'DESCRIPTOR': _INVOKECHAINREQUEST,
    '__module__': 'chainfunction_pb2'
    # @@protoc_insertion_point(class_scope:proto_gen.InvokeChainRequest)
})
_sym_db.RegisterMessage(InvokeChainRequest)

InvokeChainReply = _reflection.GeneratedProtocolMessageType('InvokeChainReply', (_message.Message,), {
    'DESCRIPTOR': _INVOKECHAINREPLY,
    '__module__': 'chainfunction_pb2'
    # @@protoc_insertion_point(class_scope:proto_gen.InvokeChainReply)
})
_sym_db.RegisterMessage(InvokeChainReply)

DESCRIPTOR._options = None

_PRODUCERCONSUMER = _descriptor.ServiceDescriptor(
    name='ProducerConsumer',
    full_name='proto_gen.ProducerConsumer',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=286,
    serialized_end=380,
    methods=[
        _descriptor.MethodDescriptor(
            name='InvokeNext',
            full_name='proto_gen.ProducerConsumer.InvokeNext',
            index=0,
            containing_service=None,
            input_type=_INVOKECHAINREQUEST,
            output_type=_INVOKECHAINREPLY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_PRODUCERCONSUMER)

DESCRIPTOR.services_by_name['ProducerConsumer'] = _PRODUCERCONSUMER

# @@protoc_insertion_point(module_scope)
