# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chainfunction_pb2 as chainfunction__pb2


class ProducerConsumerStub(object):
    """The producer and consumer functions as a single service (for simplicity)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InvokeNext = channel.unary_unary(
            '/proto_gen.ProducerConsumer/InvokeNext',
            request_serializer=chainfunction__pb2.InvokeChainRequest.SerializeToString,
            response_deserializer=chainfunction__pb2.InvokeChainReply.FromString,
        )


class ProducerConsumerServicer(object):
    """The producer and consumer functions as a single service (for simplicity)
    """

    def InvokeNext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProducerConsumerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'InvokeNext': grpc.unary_unary_rpc_method_handler(
            servicer.InvokeNext,
            request_deserializer=chainfunction__pb2.InvokeChainRequest.FromString,
            response_serializer=chainfunction__pb2.InvokeChainReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'proto_gen.ProducerConsumer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class ProducerConsumer(object):
    """The producer and consumer functions as a single service (for simplicity)
    """

    @staticmethod
    def InvokeNext(request,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto_gen.ProducerConsumer/InvokeNext',
                                             chainfunction__pb2.InvokeChainRequest.SerializeToString,
                                             chainfunction__pb2.InvokeChainReply.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
