// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto_gen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProducerConsumerClient is the client API for ProducerConsumer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProducerConsumerClient interface {
	InvokeNext(ctx context.Context, in *InvokeChainRequest, opts ...grpc.CallOption) (*InvokeChainReply, error)
}

type producerConsumerClient struct {
	cc grpc.ClientConnInterface
}

func NewProducerConsumerClient(cc grpc.ClientConnInterface) ProducerConsumerClient {
	return &producerConsumerClient{cc}
}

func (c *producerConsumerClient) InvokeNext(ctx context.Context, in *InvokeChainRequest, opts ...grpc.CallOption) (*InvokeChainReply, error) {
	out := new(InvokeChainReply)
	err := c.cc.Invoke(ctx, "/proto_gen.ProducerConsumer/InvokeNext", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProducerConsumerServer is the server API for ProducerConsumer service.
// All implementations must embed UnimplementedProducerConsumerServer
// for forward compatibility
type ProducerConsumerServer interface {
	InvokeNext(context.Context, *InvokeChainRequest) (*InvokeChainReply, error)
	mustEmbedUnimplementedProducerConsumerServer()
}

// UnimplementedProducerConsumerServer must be embedded to have forward compatible implementations.
type UnimplementedProducerConsumerServer struct {
}

func (UnimplementedProducerConsumerServer) InvokeNext(context.Context, *InvokeChainRequest) (*InvokeChainReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvokeNext not implemented")
}
func (UnimplementedProducerConsumerServer) mustEmbedUnimplementedProducerConsumerServer() {}

// UnsafeProducerConsumerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProducerConsumerServer will
// result in compilation errors.
type UnsafeProducerConsumerServer interface {
	mustEmbedUnimplementedProducerConsumerServer()
}

func RegisterProducerConsumerServer(s grpc.ServiceRegistrar, srv ProducerConsumerServer) {
	s.RegisterService(&ProducerConsumer_ServiceDesc, srv)
}

func _ProducerConsumer_InvokeNext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProducerConsumerServer).InvokeNext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_gen.ProducerConsumer/InvokeNext",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProducerConsumerServer).InvokeNext(ctx, req.(*InvokeChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProducerConsumer_ServiceDesc is the grpc.ServiceDesc for ProducerConsumer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProducerConsumer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto_gen.ProducerConsumer",
	HandlerType: (*ProducerConsumerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InvokeNext",
			Handler:    _ProducerConsumer_InvokeNext_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chainfunction.proto",
}
